package com.rohidekar.callgraph.common;

import org.apache.bcel.Repository;
import org.apache.bcel.classfile.JavaClass;

/**
 * TODO: Insert description here. (generated by ssarnobat)
 */
class DeferredRelationships {

  static void handleDeferredRelationships(Relationships relationships) {
    for (DeferredParentContainment aDeferredParentContainment :
        relationships.getDeferredParentContainments()) {
      JavaClass parentClass =
          relationships.getClassDef(aDeferredParentContainment.getParentClassName());
      handleDeferredParentContainment(relationships, aDeferredParentContainment, parentClass);
    }
    for (DeferredChildContainment containment : relationships.getDeferredChildContainment()) {
      MyClassVisitor.addContainmentRelationship(
          containment.getParentClass(), containment.getClassQualifiedName(), relationships, false);
    }
    for (DeferredSuperMethod deferredSuperMethod :
        relationships.getDeferSuperMethodRelationships()) {
      handleDeferredSuperMethod(relationships, deferredSuperMethod);
    }
  }

  private static void handleDeferredSuperMethod(
      Relationships relationships, DeferredSuperMethod deferredSuperMethod) {
    MyInstruction parentInstruction = MyMethodVisitor.getInstruction(
        deferredSuperMethod.getparentClassOrInterface(),
        deferredSuperMethod.getunqualifiedMethodName(), relationships);
    if (parentInstruction == null) {
    } else {
      System.err.println(parentInstruction.getMethodNameQualified() + " -> "
            + deferredSuperMethod.gettarget().getMethodNameQualified());
      if (!relationships.methodCallExists(deferredSuperMethod.gettarget().getMethodNameQualified(),
          parentInstruction.getMethodNameQualified())) {
        relationships.addMethodCall(parentInstruction.getMethodNameQualified(),
            deferredSuperMethod.gettarget(),
            deferredSuperMethod.gettarget().getMethodNameQualified());
      }
    }
  }

  private static void handleDeferredParentContainment(Relationships relationships,
      DeferredParentContainment aDeferredParentContainment, JavaClass parentClass) {
    if (parentClass == null) {
      try {
        parentClass = Repository.lookupClass(aDeferredParentContainment.getParentClassName());
      } catch (ClassNotFoundException e) {
    	  e.printStackTrace();
      }
    }
    if (parentClass != null) {
      MyClassVisitor.addContainmentRelationship(parentClass,
          aDeferredParentContainment.getChildClass().getClassName(), relationships, false);
    }
  }
}
