package com.rohidekar.callgraph.common;

import org.apache.bcel.classfile.JavaClass;

import com.rohidekar.callgraph.Main;

/**
 * TODO: Insert description here. (generated by ssarnobat)
 */
public class Ignorer {

  public static boolean shouldIgnore(JavaClass iClass) {
    return shouldIgnore(iClass.getClassName());
  }

  public static boolean shouldIgnore(String classFullName) {
    for (String substringToIgnore : Main.substringsToIgnore) {
      if (classFullName.contains(substringToIgnore)) {
    	  System.out.println("Ignorer.shouldIgnore() - ignoring: " + classFullName);
        return true;
      }
    }
    //System.err.println(classFullName + " was not ignored");
    return false;
  }

}
